# Auto-generated by the release workflow from the git tag.
# The CI overwrites this file before building the PyInstaller bundle, so the
# frozen app always shows the version of the tag it was built from.
__version__ = "0.2.5"
